# Copyright 2024-TODAY Todooweb (www.todooweb.com)
# License LGPL-3 or later (https://www.gnu.org/licenses/lgpl).

{
    'name': "[Extended] External Services",
    'summary': 'Changes to adapt the External Services module',
    'category': 'Manufacturing/Field Services',
    'license': 'LGPL-3',
    'version': '17.0.1.0.2',
    'author': "Todooweb (www.todooweb.com)",
    'website': "https://todooweb.com/",
    'contributors': [
        "Antonio David <antoniodavid8@gmail.com>",
        "Equipo Dev <devtodoo@gmail.com>",
        "Edgar Naranjo <edgarnaranjof@gmail.com>",
    ],
    'support': 'devtodoo@gmail.com',
    'depends': [
        'base',
        'sale',
        'sale_management',
        'account_accountant',
        'analytic',
        'project',
        'project_enterprise',
        'industry_fsm',
        'industry_fsm_sale',
        'industry_fsm_report',
        'industry_fsm_sale_report',
        'sale_project',
        'sales_team',
        'sale_timesheet',
        'purchase',
        'purchase_stock',
        'product',
        'stock',
        'sale_purchase',
        'sale_stock',
        'hr',
        'hr_timesheet',
        'stock_account'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'reports/timesheet_report.xml',
        'data/data.xml',
        'wizards/materials_selector.xml',
        'views/project_task_inherit.xml',
        'views/views_inherit.xml',
        'views/materials.xml',
    ],
    'post_init_hook': 'create_data',
    'images': ['static/description/screenshot_service.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
    'price': 79.99,
    'currency': 'EUR',
}
