# models/sprint_board.py
import json
import uuid
from datetime import date, datetime
from odoo import _, api, fields, models
from odoo.exceptions import UserError


class SprintBoard(models.Model):
    _name = "sprint.board"
    _description = "Board"
    _order = "create_date desc"
    _inherit = ["mail.thread"]

    name = fields.Char(string="Name", required=True, default=lambda self: _("New Board"))
    sprint_id = fields.Many2one("project.sprint", string="Sprint", required=True, ondelete="restrict")
    creator_id = fields.Many2one(
        "res.users", string="Creator",
        default=lambda self: self.env.user, required=True, readonly=True,
    )
    responsible_ids = fields.Many2many(
        "res.users", "sprint_board_responsible_rel", "board_id", "user_id",
        string="Editors",
    )
    viewer_ids = fields.Many2many(
        "res.users", "sprint_board_viewer_rel", "board_id", "user_id",
        string="Viewers",
    )
    state = fields.Selection(
        [("open", "Open"), ("closed", "Closed")],
        string="State", default="open", required=True, tracking=True,
    )
    date_closed = fields.Datetime(string="Close Date", readonly=True)
    ai_task_order = fields.Text(string="AI Order (JSON)")
    kiosk_token = fields.Char(string="Kiosk Token", readonly=True, copy=False)
    kiosk_active = fields.Boolean(string="Kiosk Active", default=False)
    retrospective = fields.Text(
        string="Retrospective",
        help="Sprint summary generated by AI and edited by the team. Used as context for the next sprint.",
    )
    recommendation_ids = fields.One2many(
        "sprint.board.recommendation", "board_id", string="AI Recommendations",
    )

    # ── Bug detection ─────────────────────────────────────────────────────

    @staticmethod
    def _is_bug_task(task):
        """True si la tarea es un bug.
        1. If type_id.code is set: code in ('ERR','BUG','ERROR','DEFECTO')
        2. If code is empty: type_id.name contains .error. or .bug..
        """
        # project_type (OCA) is optional — guard with getattr
        type_id = getattr(task, 'type_id', False)
        if not type_id:
            return False
        code = (type_id.code or "").strip().upper()
        if code:
            return code in ("ERR", "BUG", "ERROR", "DEFECTO", "DEFECT")
        name = (type_id.name or "").lower()
        return "error" in name or "bug" in name

    @api.model_create_multi
    def create(self, vals_list):
        today = date.today()
        for vals in vals_list:
            # Validar unicidad: no puede haber >1 board open por sprint que cubra hoy
            sprint_id = vals.get("sprint_id")
            if sprint_id:
                existing = self.search([("state", "=", "open"), ("sprint_id", "=", sprint_id)])
                covering = existing.filtered(
                    lambda b: (
                        b.sprint_id.start_date and b.sprint_id.end_date
                        and b.sprint_id.start_date.date() <= today <= b.sprint_id.end_date.date()
                    )
                )
                if covering:
                    raise UserError(_(
                        "An active board already exists for this sprint (%s). "
                        "Close it before creating a new one.",
                        covering[0].name,
                    ))
            if "name" not in vals or vals.get("name") == _("New Board"):
                sprint = self.env["project.sprint"].browse(vals.get("sprint_id"))
                if sprint:
                    vals["name"] = _("Board — %s", sprint.name)
            if "creator_id" not in vals:
                vals["creator_id"] = self.env.uid
            # Pre-cargar viewer_ids en vals (evita N writes post-create)
            if "viewer_ids" not in vals and vals.get("sprint_id"):
                sprint = self.env["project.sprint"].browse(vals["sprint_id"])
                member_partners = sprint.project_ids.mapped("message_partner_ids")
                if member_partners:
                    users = self.env["res.users"].search([("partner_id", "in", member_partners.ids)])
                    if users:
                        vals["viewer_ids"] = [(6, 0, users.ids)]
        return super().create(vals_list)

    def action_close_board(self):
        self.ensure_one()
        if self.state == "closed":
            raise UserError(_("This board is already closed."))
        # Auto-mark objectives as achieved if all their tasks are closed
        closed_states = {"1_done", "1_canceled", "03_approved"}
        for obj in self.sprint_id.objective_ids:
            if obj.state == "pending" and obj.task_ids:
                all_done = all(t.state in closed_states for t in obj.task_ids)
                if all_done:
                    obj.sudo().write({"state": "achieved"})
        self.write({
            "state": "closed",
            "date_closed": fields.Datetime.now(),
            "kiosk_active": False,
        })

    def action_activate_kiosk(self):
        self.ensure_one()
        vals = {"kiosk_active": True}
        if not self.kiosk_token:
            vals["kiosk_token"] = str(uuid.uuid4())
        self.write(vals)

    @staticmethod
    def _serialize_objective(o, closed_states):
        obj_tasks = o.task_ids
        total = len(obj_tasks)
        if total:
            completed = len(obj_tasks.filtered(lambda t: t.state in closed_states))
            rate = round((completed / total * 100), 1)
        else:
            completed = 0
            rate = round(o.completion_rate or 0.0, 1)
            if o.state == "achieved":
                rate = 100.0
        return {
            "id": o.id,
            "name": o.name,
            "state": o.state,
            "completion_rate": rate,
            "task_count": total,
            "completed_task_count": completed,
            "manual": total == 0,
            "tasks": [
                {
                    "id": t.id,
                    "name": t.name,
                    "state": t.state,
                    "is_closed": t.state in closed_states,
                    "project_name": t.project_id.name if t.project_id else None,
                    "sp": int(t.estimate_effort) if t.estimate_effort and t.estimate_effort != "00" else 0,
                    "assignees": [{"name": u.name, "initials": (u.name or "?")[:2].upper()} for u in t.user_ids],
                }
                for t in obj_tasks
            ],
        }

    def get_last_recommendations(self, limit=5):
        """Return the last N recommendations ordered by date desc."""
        self.ensure_one()
        recs = self.recommendation_ids.sorted("create_date", reverse=True)[:limit]
        return recs.read(["text", "trigger", "create_date", "feedback", "feedback_uid", "feedback_reason"])

    def get_board_data(self):
        """Payload completo del board para el componente OWL."""
        self.ensure_one()
        sprint = self.sprint_id
        tasks = sprint.task_ids
        can_edit = self.env.user in (self.creator_id | self.responsible_ids)
        closed_states = {"1_done", "1_canceled", "03_approved"}

        def sp(t):
            try:
                return int(t.estimate_effort) if t.estimate_effort and t.estimate_effort != "00" else 0
            except (ValueError, TypeError):
                return 0

        done_tasks = tasks.filtered(lambda t: t.state in closed_states)
        pending_tasks = tasks.filtered(lambda t: t.state not in closed_states)
        total_sp = sum(sp(t) for t in tasks)
        done_sp = sum(sp(t) for t in done_tasks)
        days_left = max(0, (sprint.end_date.date() - date.today()).days) if sprint.end_date else 0

        task_order = []
        if self.ai_task_order:
            try:
                task_order = json.loads(self.ai_task_order)
            except (ValueError, TypeError):
                pass

        sorted_tasks = sorted(tasks, key=lambda t: task_order.index(t.id) if t.id in task_order else 9999)

        def _blocked_days(t):
            """Days blocked: task in_progress for more than max(2, sp*1.5) days."""
            if t.state != "01_in_progress" or not t.write_date:
                return None
            elapsed = (datetime.utcnow() - t.write_date).days
            sp_val = sp(t)
            threshold = max(2, int(sp_val * 1.5)) if sp_val > 0 else 3
            return elapsed if elapsed >= threshold else None

        def serialize_task(t):
            _type_id = getattr(t, 'type_id', False)
            type_code = _type_id.code if _type_id else ""
            # Days until deadline (None if not set)
            deadline_days = None
            if t.date_deadline:
                try:
                    delta = t.date_deadline.date() - date.today()
                    deadline_days = delta.days
                except Exception:
                    pass
            return {
                "id": t.id,
                "name": t.name,
                "state": t.state,
                "priority": t.priority,
                "priority_level": int(t.priority) if t.priority and t.priority.isdigit() else 0,
                "is_priority": bool(t.priority and t.priority != "0"),
                "is_closed": t.state in closed_states,
                "is_bug": SprintBoard._is_bug_task(t),
                "type_name": _type_id.name if _type_id else "",
                "type_code": type_code,
                "sp": sp(t),
                "deadline_days": deadline_days,  # None = no date, <0 = overdue, >=0 = days remaining
                "department_id":   getattr(t, 'project_department_id', False) and t.project_department_id.id   or None,
                "department_name": getattr(t, 'project_department_id', False) and t.project_department_id.name or None,
                "blocked_days": _blocked_days(t),
                "assignees": [
                    {"id": u.id, "name": u.name, "initials": (u.name or "?")[:2].upper()}
                    for u in t.user_ids
                ],
                "url": f"/web#id={t.id}&model=project.task&view_type=form",
                "project_name": t.project_id.name if t.project_id else None,
            }

        return {
            "board": {
                "id": self.id, "name": self.name, "state": self.state,
                "can_edit": can_edit, "kiosk_active": self.kiosk_active,
                "kiosk_token": self.kiosk_token if can_edit else None,
                "date_closed": self.date_closed.isoformat() if self.date_closed else None,
            },
            "sprint": {
                "id": sprint.id, "name": sprint.name, "state": sprint.state,
                "start_date": sprint.start_date.date().isoformat() if sprint.start_date else None,
                "end_date": sprint.end_date.date().isoformat() if sprint.end_date else None,
                "days_left": days_left,
            },
            "kpis": {
                "total_tasks": len(tasks), "done_tasks": len(done_tasks),
                "pending_tasks": len(pending_tasks),
                "pct": round(len(done_tasks) / len(tasks) * 100) if tasks else 0,
                "total_sp": total_sp, "done_sp": done_sp, "pending_sp": total_sp - done_sp,
                "days_left": days_left,
            },
            "tasks": [serialize_task(t) for t in sorted_tasks],
            "objectives": [
                self._serialize_objective(o, closed_states)
                for o in sprint.objective_ids
            ],
            "recommendations": self.get_last_recommendations(),
            "health": self._compute_health(sprint, tasks, done_tasks, done_sp, total_sp),
            "prediction": self._compute_prediction(sprint, tasks, done_tasks),
            "comparison": self._compute_comparison(sprint, tasks, done_tasks),
        }

    # ── A) Health indicator ───────────────────────────────────────────────

    def _compute_health(self, sprint, tasks, done_tasks, done_sp, total_sp):
        """🟢 On track / 🟡 At risk / 🔴 Critical."""
        if not sprint.start_date or not sprint.end_date or not tasks:
            return {"status": "unknown", "label": "Sin datos", "diff": 0}
        total_days  = max(1, (sprint.end_date.date() - sprint.start_date.date()).days)
        elapsed     = max(0, (date.today() - sprint.start_date.date()).days)
        time_pct    = min(100, round(elapsed / total_days * 100))
        progress_pct = round(len(done_tasks) / len(tasks) * 100)
        diff = progress_pct - time_pct
        bug_count = len([t for t in tasks
                         if self._is_bug_task(t) and t.state not in {"1_done", "1_canceled", "03_approved"}])
        if diff >= -10 and bug_count <= 2:
            status, label = "on_track",  "On track"
        elif diff >= -25 and bug_count <= 4:
            status, label = "at_risk",   "At risk"
        else:
            status, label = "critical",  "Critical"
        return {"status": status, "label": label, "diff": diff,
                "time_pct": time_pct, "progress_pct": progress_pct}

    # ── D) Completion prediction ───────────────────────────────────────────

    def _compute_prediction(self, sprint, tasks, done_tasks):
        """Real velocity → completion prediction."""
        if not sprint.start_date or not sprint.end_date or not tasks:
            return None
        days_elapsed = max(1, (date.today() - sprint.start_date.date()).days)
        days_left    = max(0, (sprint.end_date.date() - date.today()).days)
        velocity     = round(len(done_tasks) / days_elapsed, 2)  # tasks/day
        pending      = len(tasks) - len(done_tasks)
        if velocity > 0:
            days_needed = round(pending / velocity, 1)
            will_complete = days_needed <= days_left
            projected_done = min(len(tasks), len(done_tasks) + round(velocity * days_left))
        else:
            days_needed   = None
            will_complete  = False
            projected_done = len(done_tasks)
        return {
            "velocity":       velocity,
            "days_left":      days_left,
            "pending":        pending,
            "projected_done": projected_done,
            "total_tasks":    len(tasks),
            "will_complete":  will_complete,
            "pct_chance":     min(100, round((projected_done / len(tasks)) * 100)) if tasks else 0,
        }

    # ── G) Comparativa sprints anteriores ────────────────────────────────

    def _compute_comparison(self, sprint, tasks, done_tasks):
        """Compare with previous sprint and historical average."""
        if not sprint.project_ids:
            return None
        closed = {"1_done", "1_canceled", "03_approved"}
        project_ids = sprint.project_ids.ids

        def _sprint_metrics(s):
            t = s.task_ids
            done = t.filtered(lambda x: x.state in closed)
            total_days = max(1, (s.end_date.date() - s.start_date.date()).days) if s.start_date and s.end_date else 1
            return {
                "velocity":    round(len(done) / total_days, 2),
                "completion":  round(len(done) / len(t) * 100) if t else 0,
                "done_tasks":  len(done),
                "total_tasks": len(t),
            }

        prev_sprints = self.env["project.sprint"].search([
            ("project_ids", "in", project_ids),
            ("state", "=", "closed"),
            ("id", "!=", sprint.id),
        ], order="end_date desc", limit=10)

        if not prev_sprints:
            return None

        # Sprint anterior
        prev  = _sprint_metrics(prev_sprints[0])
        # Historical average
        all_m = [_sprint_metrics(s) for s in prev_sprints]
        avg   = {
            "velocity":   round(sum(m["velocity"]   for m in all_m) / len(all_m), 2),
            "completion": round(sum(m["completion"] for m in all_m) / len(all_m)),
        }
        # Current metrics (estimated at current pace)
        days_elapsed = max(1, (date.today() - sprint.start_date.date()).days) if sprint.start_date else 1
        curr_velocity = round(len(done_tasks) / days_elapsed, 2)

        def _delta(curr, ref):
            if ref == 0: return 0
            return round((curr - ref) / ref * 100)

        return {
            "vs_prev": {
                "velocity_delta":    _delta(curr_velocity, prev["velocity"]),
                "sprint_name":       prev_sprints[0].name,
            },
            "vs_avg": {
                "velocity_delta":    _delta(curr_velocity, avg["velocity"]),
                "completion_avg":    avg["completion"],
                "sprint_count":      len(prev_sprints),
            },
            "current_velocity": curr_velocity,
        }

    def action_sync_viewers(self):
        """Sincroniza viewer_ids con todos los usuarios asignados a tareas del sprint
        with Board/Viewer group. Useful for already created boards."""
        self.ensure_one()
        viewer_group = self.env.ref(
            "todoo_sprint_board_project.group_sprint_board_viewer",
            raise_if_not_found=False,
        )
        if not viewer_group:
            return
        task_users = self.sprint_id.task_ids.mapped("user_ids").filtered(
            lambda u: not u.share and viewer_group in u.groups_id
        )
        already = self.viewer_ids | self.responsible_ids | self.creator_id
        to_add = task_users - already
        if to_add:
            self.write({"viewer_ids": [(4, u.id) for u in to_add]})

    def _cron_notify_missing_board(self):
        """Cron diario: notifica si no hay board open que cubra hoy."""
        today = date.today()
        active_boards = self.search([("state", "=", "open")])
        has_today = any(
            b.sprint_id.start_date and b.sprint_id.end_date and
            b.sprint_id.start_date.date() <= today <= b.sprint_id.end_date.date()
            for b in active_boards
        )
        if has_today:
            return
        last_closed = self.search([("state", "=", "closed")], order="date_closed desc", limit=1)
        if not last_closed:
            return
        recipients = last_closed.responsible_ids | last_closed.creator_id
        if not recipients:
            return
        last_closed.message_post(
            body=_("No active Board found for today (%s). Do you want to create one?",
                   today.strftime("%d/%m/%Y")),
            partner_ids=recipients.mapped("partner_id").ids,
            message_type="notification",
            subtype_xmlid="mail.mt_note",
        )


class SprintBoardRecommendation(models.Model):
    _name = "sprint.board.recommendation"
    _description = "Board AI Recommendation"
    _order = "create_date desc"

    board_id    = fields.Many2one("sprint.board", string="Board", required=True, ondelete="cascade")
    text        = fields.Text(string="Text", required=True)
    trigger     = fields.Char(string="Trigger", required=True)
    feedback    = fields.Selection(
        [("positive", "Useful"), ("negative", "Not Useful")],
        string="Feedback", default=None,
    )
    feedback_uid = fields.Many2one(
        "res.users", string="Rated By", readonly=True,
    )
    feedback_reason = fields.Text(
        string="Feedback Reason",
        help="Why this recommendation was not useful (helps improve the AI)",
    )


class ProjectTaskBoardSync(models.Model):
    """Sincroniza viewer_ids del board cuando se asignan tareas."""
    _inherit = "project.task"

    def _sync_board_viewers(self):
        """Add to viewer_ids the users assigned to sprint tasks
        que tengan el grupo Board/Viewer o Board/Editor."""
        viewer_group = self.env.ref(
            "todoo_sprint_board_project.group_sprint_board_viewer",
            raise_if_not_found=False,
        )
        if not viewer_group:
            return
        for task in self.filtered(lambda t: t.sprint_id and t.user_ids):
            boards = self.env["sprint.board"].search([
                ("sprint_id", "=", task.sprint_id.id),
                ("state", "=", "open"),
            ])
            if not boards:
                continue
            # Usuarios asignados que tienen el grupo Viewer/Editor
            new_viewers = task.user_ids.filtered(
                lambda u: not u.share and viewer_group in u.groups_id
            )
            if not new_viewers:
                continue
            for board in boards:
                already = board.viewer_ids | board.responsible_ids | board.creator_id
                to_add = new_viewers - already
                if to_add:
                    board.sudo().write({"viewer_ids": [(4, u.id) for u in to_add]})

    def write(self, vals):
        result = super().write(vals)
        if "user_ids" in vals:
            self._sync_board_viewers()
        return result

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        records._sync_board_viewers()
        return records
