# tests/test_sprint_board_model.py
import uuid
from odoo.tests.common import TransactionCase
from odoo.tests import tagged


@tagged("post_install", "-at_install", "sprint_board")
class TestSprintBoardModel(TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.user_editor = cls.env["res.users"].create({
            "name": "Editor Test",
            "login": "sprint_editor_test",
            "email": "editor@test.com",
            "groups_id": [(6, 0, [
                cls.env.ref("todoo_sprint_board_project.group_sprint_board_editor").id,
                cls.env.ref("project.group_project_user").id,
            ])],
        })
        cls.project = cls.env["project.project"].create({"name": "Proyecto Test Sprint Board"})
        cls.sprint = cls.env["project.sprint"].create({
            "name": "Sprint Test",
            "start_date": "2026-06-01 00:00:00",
            "end_date": "2026-06-14 23:59:59",
            "state": "in_progress",
            "project_ids": [(6, 0, [cls.project.id])],
        })

    def test_B01_create_board_minimal(self):
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        self.assertEqual(board.state, "open")
        self.assertEqual(board.creator_id, self.env.user)
        self.assertIn("Sprint Test", board.name)

    def test_B02_name_autogenerated(self):
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        self.assertIn("Sprint Test", board.name)

    def test_B03_viewer_ids_prefilled(self):
        # En Odoo 17 project.project no tiene member_ids; usamos message_subscribe
        self.project.message_subscribe(partner_ids=[self.user_editor.partner_id.id])
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        self.assertIn(self.user_editor, board.viewer_ids)

    def test_B04_close_board(self):
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        board.action_close_board()
        self.assertEqual(board.state, "closed")
        self.assertIsNotNone(board.date_closed)

    def test_B05_sprint_id_required(self):
        with self.assertRaises(Exception):
            self.env["sprint.board"].create({"name": "Sin sprint"})

    def test_B05b_unicidad_board_activo_por_sprint(self):
        """No puede haber dos boards open para el mismo sprint que cubra hoy."""
        from odoo.exceptions import UserError
        from odoo.fields import Datetime
        # Sprint que cubre hoy
        from datetime import date, timedelta
        today = date.today()
        sprint_hoy = self.env["project.sprint"].create({
            "name": "Sprint Hoy",
            "start_date": Datetime.to_datetime(today - timedelta(days=1)),
            "end_date":   Datetime.to_datetime(today + timedelta(days=5)),
            "state": "in_progress",
        })
        # Primer board: debe crearse sin error
        self.env["sprint.board"].create({"sprint_id": sprint_hoy.id})
        # Segundo board para el mismo sprint: debe lanzar UserError
        with self.assertRaises(UserError):
            self.env["sprint.board"].create({"sprint_id": sprint_hoy.id})

    def test_B06_kiosk_token_generated(self):
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        self.assertFalse(board.kiosk_token)
        board.action_activate_kiosk()
        self.assertTrue(board.kiosk_token)
        uuid.UUID(board.kiosk_token)

    def test_B07_kiosk_deactivate_preserves_token(self):
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        board.action_activate_kiosk()
        token = board.kiosk_token
        board.write({"kiosk_active": False})
        self.assertEqual(board.kiosk_token, token)
        self.assertFalse(board.kiosk_active)

    def test_R01_create_recommendation(self):
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        rec = self.env["sprint.board.recommendation"].create({
            "board_id": board.id,
            "text": "Focus on bugs first.",
            "trigger": "On board open",
        })
        self.assertEqual(rec.board_id, board)
        self.assertEqual(len(board.recommendation_ids), 1)

    def test_R02_max_5_recommendations(self):
        board = self.env["sprint.board"].create({"sprint_id": self.sprint.id})
        for i in range(7):
            self.env["sprint.board.recommendation"].create({
                "board_id": board.id,
                "text": f"Recommendation {i}",
                "trigger": "test",
            })
        result = board.get_last_recommendations()
        self.assertLessEqual(len(result), 5)
